const FIRST_NAMES = [
  "Ana",
  "Bruno",
  "Carla",
  "Daniel",
  "Eduarda",
  "Felipe",
  "Gabriela",
  "Henrique",
  "Isabela",
  "Joao",
  "Karen",
  "Lucas",
  "Mariana",
  "Nicolas",
  "Olivia",
  "Paulo",
  "Quezia",
  "Rafael",
  "Sabrina",
  "Tiago",
  "Ursula",
  "Valentina",
  "William",
  "Yasmin",
  "Aline",
  "Bianca",
  "Camila",
  "Diego",
  "Elisa",
  "Fabio",
  "Giovana",
  "Heitor",
  "Iago",
  "Juliana",
  "Leandro",
  "Melissa",
  "Natalia",
  "Otavio",
  "Priscila",
  "Renato",
  "Simone",
  "Talita",
  "Vinicius",
  "Caio",
  "Debora",
  "Erika",
  "Fernando",
  "Larissa",
];

const LAST_NAMES = [
  "Silva",
  "Souza",
  "Oliveira",
  "Santos",
  "Lima",
  "Costa",
  "Pereira",
  "Rodrigues",
  "Almeida",
  "Nascimento",
  "Ferreira",
  "Gomes",
  "Martins",
  "Araujo",
  "Melo",
  "Barbosa",
  "Ribeiro",
  "Cardoso",
  "Teixeira",
  "Batista",
  "Moreira",
  "Freitas",
  "Rocha",
  "Monteiro",
  "Vieira",
  "Dias",
  "Machado",
  "Moura",
  "Castro",
  "Campos",
];

const INGREDIENT_CATALOG = [
  { name: "Farinha de Trigo", unit: "kg", stock: [40, 180] },
  { name: "Acucar", unit: "kg", stock: [20, 120] },
  { name: "Sal", unit: "kg", stock: [10, 60] },
  { name: "Fermento Biologico", unit: "kg", stock: [4, 25] },
  { name: "Ovos", unit: "un", stock: [120, 600] },
  { name: "Leite", unit: "L", stock: [30, 120] },
  { name: "Manteiga", unit: "kg", stock: [8, 40] },
  { name: "Chocolate em Po", unit: "kg", stock: [8, 35] },
  { name: "Cafe Moido", unit: "kg", stock: [8, 35] },
  { name: "Queijo Minas", unit: "kg", stock: [10, 45] },
  { name: "Presunto", unit: "kg", stock: [8, 35] },
  { name: "Frango Desfiado", unit: "kg", stock: [10, 40] },
  { name: "Cenoura", unit: "kg", stock: [8, 35] },
  { name: "Oleo", unit: "L", stock: [10, 50] },
  { name: "Laranja", unit: "kg", stock: [12, 50] },
  { name: "Polvilho", unit: "kg", stock: [8, 35] },
  { name: "Requeijao", unit: "kg", stock: [6, 20] },
  { name: "Carne Moida", unit: "kg", stock: [8, 28] },
  { name: "Limao", unit: "kg", stock: [6, 25] },
  { name: "Creme de Leite", unit: "L", stock: [6, 24] },
  { name: "Leite Condensado", unit: "L", stock: [6, 24] },
  { name: "Queijo Mussarela", unit: "kg", stock: [10, 45] },
  { name: "Tomate", unit: "kg", stock: [8, 28] },
  { name: "Alho-Poro", unit: "kg", stock: [4, 16] },
  { name: "Bacon", unit: "kg", stock: [5, 20] },
  { name: "Calabresa", unit: "kg", stock: [5, 20] },
  { name: "Milho", unit: "kg", stock: [6, 18] },
  { name: "Ervilha", unit: "kg", stock: [4, 16] },
  { name: "Molho de Tomate", unit: "L", stock: [6, 24] },
  { name: "Cebola", unit: "kg", stock: [8, 25] },
  { name: "Alho", unit: "kg", stock: [4, 12] },
  { name: "Canela", unit: "kg", stock: [1, 5] },
  { name: "Baunilha", unit: "ml", stock: [500, 2500] },
  { name: "Coco Ralado", unit: "kg", stock: [3, 12] },
  { name: "Uva Passa", unit: "kg", stock: [2, 10] },
  { name: "Aveia", unit: "kg", stock: [4, 16] },
  { name: "Farinha Integral", unit: "kg", stock: [8, 28] },
  { name: "Mel", unit: "L", stock: [3, 12] },
  { name: "Goiabada", unit: "kg", stock: [4, 18] },
  { name: "Doce de Leite", unit: "kg", stock: [4, 18] },
  { name: "Morango", unit: "kg", stock: [4, 15] },
  { name: "Banana", unit: "kg", stock: [4, 15] },
  { name: "Abacaxi", unit: "kg", stock: [4, 15] },
  { name: "Maca", unit: "kg", stock: [4, 15] },
  { name: "Nozes", unit: "kg", stock: [2, 8] },
  { name: "Amendoim", unit: "kg", stock: [3, 10] },
  { name: "Chantilly", unit: "L", stock: [4, 16] },
  { name: "Iogurte", unit: "L", stock: [6, 20] },
  { name: "Granola", unit: "kg", stock: [3, 12] },
  { name: "Cha Preto", unit: "kg", stock: [1, 5] },
  { name: "Leite em Po", unit: "kg", stock: [3, 12] },
  { name: "Salsicha", unit: "kg", stock: [4, 14] },
  { name: "Batata", unit: "kg", stock: [8, 28] },
  { name: "Catupiry", unit: "kg", stock: [4, 14] },
  { name: "Palmito", unit: "kg", stock: [3, 12] },
  { name: "Ricota", unit: "kg", stock: [3, 12] },
  { name: "Espinafre", unit: "kg", stock: [3, 10] },
  { name: "Maracuja", unit: "kg", stock: [3, 12] },
  { name: "Cacau", unit: "kg", stock: [2, 8] },
  { name: "Creme de Avela", unit: "kg", stock: [2, 8] },
];

const PRODUCT_FAMILIES = [
  {
    name: "Pao Frances",
    category: "Panificacao",
    basePrice: 1.1,
    popularity: 10,
    quantityRange: [2, 10],
    recipe: [
      ["Farinha de Trigo", 0.12],
      ["Fermento Biologico", 0.01],
      ["Sal", 0.005],
    ],
    variants: [
      { suffix: "Tradicional", multiplier: 1, popularity: 1 },
      { suffix: "Da Casa", multiplier: 1.08, popularity: 0.9 },
      { suffix: "Crocante", multiplier: 1.12, popularity: 0.8 },
      { suffix: "Integral", multiplier: 1.2, popularity: 0.7, extraRecipe: [["Farinha Integral", 0.05]] },
    ],
  },
  {
    name: "Pao de Queijo",
    category: "Panificacao",
    basePrice: 3.2,
    popularity: 8.5,
    quantityRange: [1, 6],
    recipe: [
      ["Polvilho", 0.08],
      ["Queijo Minas", 0.04],
      ["Leite", 0.03],
      ["Ovos", 1],
    ],
    variants: [
      { suffix: "Tradicional", multiplier: 1, popularity: 1 },
      { suffix: "Mini", multiplier: 0.78, popularity: 1.1 },
      { suffix: "Recheado", multiplier: 1.25, popularity: 0.8, extraRecipe: [["Requeijao", 0.03]] },
      { suffix: "Multigraos", multiplier: 1.18, popularity: 0.6, extraRecipe: [["Aveia", 0.02]] },
    ],
  },
  {
    name: "Croissant",
    category: "Panificacao",
    basePrice: 7.5,
    popularity: 5.8,
    quantityRange: [1, 3],
    recipe: [
      ["Farinha de Trigo", 0.14],
      ["Manteiga", 0.05],
      ["Leite", 0.03],
      ["Fermento Biologico", 0.01],
    ],
    variants: [
      { suffix: "Tradicional", multiplier: 1, popularity: 1 },
      { suffix: "com Queijo", multiplier: 1.18, popularity: 0.85, extraRecipe: [["Queijo Mussarela", 0.03]] },
      { suffix: "com Chocolate", multiplier: 1.22, popularity: 0.9, extraRecipe: [["Chocolate em Po", 0.02]] },
      { suffix: "Amanteigado", multiplier: 1.15, popularity: 0.7 },
    ],
  },
  {
    name: "Baguete",
    category: "Panificacao",
    basePrice: 6.8,
    popularity: 4.5,
    quantityRange: [1, 3],
    recipe: [
      ["Farinha de Trigo", 0.18],
      ["Fermento Biologico", 0.01],
      ["Sal", 0.005],
    ],
    variants: [
      { suffix: "Tradicional", multiplier: 1, popularity: 1 },
      { suffix: "Integral", multiplier: 1.2, popularity: 0.7, extraRecipe: [["Farinha Integral", 0.06]] },
      { suffix: "com Alho", multiplier: 1.15, popularity: 0.65, extraRecipe: [["Alho", 0.01]] },
      { suffix: "Especial", multiplier: 1.12, popularity: 0.7 },
    ],
  },
  {
    name: "Bisnaguinha",
    category: "Panificacao",
    basePrice: 5.2,
    popularity: 4.2,
    quantityRange: [1, 4],
    recipe: [
      ["Farinha de Trigo", 0.15],
      ["Leite", 0.04],
      ["Manteiga", 0.02],
      ["Fermento Biologico", 0.01],
    ],
    variants: [
      { suffix: "Tradicional", multiplier: 1, popularity: 1 },
      { suffix: "Integral", multiplier: 1.16, popularity: 0.65, extraRecipe: [["Farinha Integral", 0.05]] },
      { suffix: "de Leite", multiplier: 1.08, popularity: 0.8 },
      { suffix: "com Mel", multiplier: 1.14, popularity: 0.6, extraRecipe: [["Mel", 0.01]] },
    ],
  },
  {
    name: "Pao de Batata",
    category: "Panificacao",
    basePrice: 6.4,
    popularity: 5.2,
    quantityRange: [1, 4],
    recipe: [
      ["Farinha de Trigo", 0.12],
      ["Batata", 0.08],
      ["Leite", 0.03],
      ["Manteiga", 0.02],
    ],
    variants: [
      { suffix: "Tradicional", multiplier: 1, popularity: 1 },
      { suffix: "com Catupiry", multiplier: 1.22, popularity: 0.95, extraRecipe: [["Catupiry", 0.03]] },
      { suffix: "com Frango", multiplier: 1.28, popularity: 0.8, extraRecipe: [["Frango Desfiado", 0.04]] },
      { suffix: "com Queijo", multiplier: 1.2, popularity: 0.85, extraRecipe: [["Queijo Mussarela", 0.03]] },
    ],
  },
  {
    name: "Pao na Chapa",
    category: "Panificacao",
    basePrice: 4.8,
    popularity: 6.5,
    quantityRange: [1, 3],
    recipe: [
      ["Farinha de Trigo", 0.12],
      ["Manteiga", 0.02],
      ["Sal", 0.004],
    ],
    variants: [
      { suffix: "com Manteiga", multiplier: 1, popularity: 1 },
      { suffix: "com Requeijao", multiplier: 1.18, popularity: 0.8, extraRecipe: [["Requeijao", 0.03]] },
      { suffix: "com Queijo", multiplier: 1.22, popularity: 0.75, extraRecipe: [["Queijo Mussarela", 0.03]] },
      { suffix: "Especial", multiplier: 1.12, popularity: 0.65 },
    ],
  },
  {
    name: "Sonho",
    category: "Confeitaria",
    basePrice: 7.2,
    popularity: 5.4,
    quantityRange: [1, 3],
    recipe: [
      ["Farinha de Trigo", 0.12],
      ["Acucar", 0.03],
      ["Leite", 0.03],
      ["Ovos", 1],
    ],
    variants: [
      { suffix: "de Creme", multiplier: 1, popularity: 1, extraRecipe: [["Creme de Leite", 0.03]] },
      { suffix: "de Doce de Leite", multiplier: 1.18, popularity: 0.85, extraRecipe: [["Doce de Leite", 0.03]] },
      { suffix: "de Goiabada", multiplier: 1.12, popularity: 0.75, extraRecipe: [["Goiabada", 0.03]] },
      { suffix: "de Chocolate", multiplier: 1.2, popularity: 0.8, extraRecipe: [["Chocolate em Po", 0.02]] },
    ],
  },
  {
    name: "Donut",
    category: "Confeitaria",
    basePrice: 6.8,
    popularity: 4.2,
    quantityRange: [1, 3],
    recipe: [
      ["Farinha de Trigo", 0.11],
      ["Acucar", 0.03],
      ["Leite", 0.03],
      ["Ovos", 1],
    ],
    variants: [
      { suffix: "Glaceado", multiplier: 1, popularity: 1 },
      { suffix: "de Chocolate", multiplier: 1.15, popularity: 0.95, extraRecipe: [["Chocolate em Po", 0.02]] },
      { suffix: "de Morango", multiplier: 1.18, popularity: 0.7, extraRecipe: [["Morango", 0.03]] },
      { suffix: "de Coco", multiplier: 1.14, popularity: 0.6, extraRecipe: [["Coco Ralado", 0.02]] },
    ],
  },
  {
    name: "Bolo de Cenoura",
    category: "Confeitaria",
    basePrice: 27,
    popularity: 3.8,
    quantityRange: [1, 2],
    recipe: [
      ["Farinha de Trigo", 0.3],
      ["Acucar", 0.18],
      ["Ovos", 3],
      ["Cenoura", 0.25],
      ["Oleo", 0.08],
      ["Fermento Biologico", 0.02],
    ],
    variants: [
      { suffix: "Inteiro", multiplier: 1, popularity: 1 },
      { suffix: "com Cobertura", multiplier: 1.18, popularity: 0.95, extraRecipe: [["Chocolate em Po", 0.04]] },
      { suffix: "Fatia", multiplier: 0.34, popularity: 1.15 },
      { suffix: "Mini", multiplier: 0.55, popularity: 0.85 },
    ],
  },
  {
    name: "Bolo de Chocolate",
    category: "Confeitaria",
    basePrice: 29,
    popularity: 3.6,
    quantityRange: [1, 2],
    recipe: [
      ["Farinha de Trigo", 0.28],
      ["Acucar", 0.2],
      ["Ovos", 3],
      ["Chocolate em Po", 0.08],
      ["Leite", 0.08],
      ["Fermento Biologico", 0.02],
    ],
    variants: [
      { suffix: "Inteiro", multiplier: 1, popularity: 1 },
      { suffix: "Premium", multiplier: 1.22, popularity: 0.8, extraRecipe: [["Cacau", 0.03]] },
      { suffix: "Fatia", multiplier: 0.35, popularity: 1.1 },
      { suffix: "com Brigadeiro", multiplier: 1.25, popularity: 0.85, extraRecipe: [["Leite Condensado", 0.04]] },
    ],
  },
  {
    name: "Bolo de Fuba",
    category: "Confeitaria",
    basePrice: 23,
    popularity: 3.1,
    quantityRange: [1, 2],
    recipe: [
      ["Farinha de Trigo", 0.24],
      ["Acucar", 0.16],
      ["Leite", 0.08],
      ["Ovos", 2],
      ["Manteiga", 0.04],
    ],
    variants: [
      { suffix: "Tradicional", multiplier: 1, popularity: 1 },
      { suffix: "com Coco", multiplier: 1.12, popularity: 0.75, extraRecipe: [["Coco Ralado", 0.03]] },
      { suffix: "Fatia", multiplier: 0.34, popularity: 1.05 },
      { suffix: "com Goiabada", multiplier: 1.18, popularity: 0.7, extraRecipe: [["Goiabada", 0.04]] },
    ],
  },
  {
    name: "Torta de Limao",
    category: "Confeitaria",
    basePrice: 30,
    popularity: 2.8,
    quantityRange: [1, 2],
    recipe: [
      ["Farinha de Trigo", 0.22],
      ["Manteiga", 0.08],
      ["Limao", 0.12],
      ["Creme de Leite", 0.08],
      ["Leite Condensado", 0.08],
    ],
    variants: [
      { suffix: "Inteira", multiplier: 1, popularity: 1 },
      { suffix: "Fatia", multiplier: 0.33, popularity: 1.1 },
      { suffix: "com Chantilly", multiplier: 1.14, popularity: 0.8, extraRecipe: [["Chantilly", 0.04]] },
      { suffix: "Especial", multiplier: 1.2, popularity: 0.7 },
    ],
  },
  {
    name: "Cookie",
    category: "Confeitaria",
    basePrice: 5.4,
    popularity: 4.8,
    quantityRange: [1, 5],
    recipe: [
      ["Farinha de Trigo", 0.08],
      ["Acucar", 0.03],
      ["Manteiga", 0.03],
      ["Ovos", 1],
    ],
    variants: [
      { suffix: "com Chocolate", multiplier: 1, popularity: 1, extraRecipe: [["Chocolate em Po", 0.02]] },
      { suffix: "de Aveia", multiplier: 1.08, popularity: 0.8, extraRecipe: [["Aveia", 0.03]] },
      { suffix: "com Nozes", multiplier: 1.18, popularity: 0.6, extraRecipe: [["Nozes", 0.02]] },
      { suffix: "com Gotas de Cacau", multiplier: 1.15, popularity: 0.7, extraRecipe: [["Cacau", 0.02]] },
    ],
  },
  {
    name: "Brownie",
    category: "Confeitaria",
    basePrice: 8.2,
    popularity: 3.7,
    quantityRange: [1, 3],
    recipe: [
      ["Chocolate em Po", 0.05],
      ["Farinha de Trigo", 0.08],
      ["Acucar", 0.05],
      ["Ovos", 2],
      ["Manteiga", 0.03],
    ],
    variants: [
      { suffix: "Tradicional", multiplier: 1, popularity: 1 },
      { suffix: "com Nozes", multiplier: 1.16, popularity: 0.75, extraRecipe: [["Nozes", 0.02]] },
      { suffix: "com Creme de Avela", multiplier: 1.25, popularity: 0.65, extraRecipe: [["Creme de Avela", 0.03]] },
      { suffix: "Mini", multiplier: 0.7, popularity: 0.9 },
    ],
  },
  {
    name: "Muffin",
    category: "Confeitaria",
    basePrice: 7.5,
    popularity: 3.9,
    quantityRange: [1, 3],
    recipe: [
      ["Farinha de Trigo", 0.1],
      ["Acucar", 0.03],
      ["Ovos", 1],
      ["Leite", 0.03],
    ],
    variants: [
      { suffix: "de Chocolate", multiplier: 1, popularity: 1, extraRecipe: [["Chocolate em Po", 0.02]] },
      { suffix: "de Banana", multiplier: 1.08, popularity: 0.75, extraRecipe: [["Banana", 0.05]] },
      { suffix: "de Maca e Canela", multiplier: 1.12, popularity: 0.7, extraRecipe: [["Maca", 0.05], ["Canela", 0.005]] },
      { suffix: "com Coco", multiplier: 1.1, popularity: 0.65, extraRecipe: [["Coco Ralado", 0.02]] },
    ],
  },
  {
    name: "Coxinha",
    category: "Salgados",
    basePrice: 8.5,
    popularity: 7.2,
    quantityRange: [1, 4],
    recipe: [
      ["Farinha de Trigo", 0.1],
      ["Frango Desfiado", 0.07],
      ["Manteiga", 0.02],
      ["Sal", 0.004],
    ],
    variants: [
      { suffix: "Tradicional", multiplier: 1, popularity: 1 },
      { suffix: "com Catupiry", multiplier: 1.18, popularity: 0.95, extraRecipe: [["Catupiry", 0.03]] },
      { suffix: "Mini", multiplier: 0.72, popularity: 1.1 },
      { suffix: "Assada", multiplier: 1.1, popularity: 0.8 },
    ],
  },
  {
    name: "Esfiha",
    category: "Salgados",
    basePrice: 7.8,
    popularity: 5.3,
    quantityRange: [1, 4],
    recipe: [
      ["Farinha de Trigo", 0.11],
      ["Sal", 0.004],
      ["Fermento Biologico", 0.01],
    ],
    variants: [
      { suffix: "de Carne", multiplier: 1, popularity: 1, extraRecipe: [["Carne Moida", 0.05], ["Cebola", 0.02]] },
      { suffix: "de Frango", multiplier: 1.06, popularity: 0.85, extraRecipe: [["Frango Desfiado", 0.05]] },
      { suffix: "de Queijo", multiplier: 1.05, popularity: 0.8, extraRecipe: [["Queijo Mussarela", 0.04]] },
      { suffix: "de Calabresa", multiplier: 1.1, popularity: 0.7, extraRecipe: [["Calabresa", 0.04]] },
    ],
  },
  {
    name: "Empada",
    category: "Salgados",
    basePrice: 8.2,
    popularity: 4.8,
    quantityRange: [1, 4],
    recipe: [
      ["Farinha de Trigo", 0.1],
      ["Manteiga", 0.03],
      ["Ovos", 1],
    ],
    variants: [
      { suffix: "de Frango", multiplier: 1, popularity: 1, extraRecipe: [["Frango Desfiado", 0.05], ["Milho", 0.02]] },
      { suffix: "de Palmito", multiplier: 1.12, popularity: 0.7, extraRecipe: [["Palmito", 0.05], ["Creme de Leite", 0.02]] },
      { suffix: "de Queijo", multiplier: 1.08, popularity: 0.8, extraRecipe: [["Queijo Mussarela", 0.04]] },
      { suffix: "de Bacon", multiplier: 1.14, popularity: 0.6, extraRecipe: [["Bacon", 0.04]] },
    ],
  },
  {
    name: "Pastel Assado",
    category: "Salgados",
    basePrice: 8.8,
    popularity: 4.4,
    quantityRange: [1, 3],
    recipe: [
      ["Farinha de Trigo", 0.11],
      ["Manteiga", 0.02],
      ["Sal", 0.004],
    ],
    variants: [
      { suffix: "de Queijo", multiplier: 1, popularity: 1, extraRecipe: [["Queijo Mussarela", 0.05]] },
      { suffix: "de Carne", multiplier: 1.08, popularity: 0.8, extraRecipe: [["Carne Moida", 0.05]] },
      { suffix: "de Frango", multiplier: 1.08, popularity: 0.75, extraRecipe: [["Frango Desfiado", 0.05]] },
      { suffix: "de Presunto e Queijo", multiplier: 1.14, popularity: 0.85, extraRecipe: [["Presunto", 0.04], ["Queijo Mussarela", 0.04]] },
    ],
  },
  {
    name: "Quiche",
    category: "Salgados",
    basePrice: 11.5,
    popularity: 2.9,
    quantityRange: [1, 2],
    recipe: [
      ["Farinha de Trigo", 0.12],
      ["Manteiga", 0.04],
      ["Ovos", 2],
      ["Creme de Leite", 0.03],
    ],
    variants: [
      { suffix: "de Alho-Poro", multiplier: 1, popularity: 1, extraRecipe: [["Alho-Poro", 0.05]] },
      { suffix: "de Queijo", multiplier: 1.1, popularity: 0.8, extraRecipe: [["Queijo Mussarela", 0.04]] },
      { suffix: "de Espinafre", multiplier: 1.08, popularity: 0.7, extraRecipe: [["Espinafre", 0.04], ["Ricota", 0.03]] },
      { suffix: "de Bacon", multiplier: 1.16, popularity: 0.65, extraRecipe: [["Bacon", 0.04]] },
    ],
  },
  {
    name: "Misto Quente",
    category: "Salgados",
    basePrice: 9.4,
    popularity: 5.9,
    quantityRange: [1, 3],
    recipe: [
      ["Farinha de Trigo", 0.12],
      ["Presunto", 0.05],
      ["Queijo Mussarela", 0.05],
      ["Manteiga", 0.01],
    ],
    variants: [
      { suffix: "Tradicional", multiplier: 1, popularity: 1 },
      { suffix: "na Chapa", multiplier: 1.08, popularity: 0.95 },
      { suffix: "com Requeijao", multiplier: 1.16, popularity: 0.7, extraRecipe: [["Requeijao", 0.03]] },
      { suffix: "Especial", multiplier: 1.18, popularity: 0.65, extraRecipe: [["Tomate", 0.03]] },
    ],
  },
  {
    name: "Sanduiche Natural",
    category: "Salgados",
    basePrice: 10.8,
    popularity: 3.6,
    quantityRange: [1, 2],
    recipe: [
      ["Farinha de Trigo", 0.12],
      ["Frango Desfiado", 0.05],
      ["Tomate", 0.03],
      ["Requeijao", 0.03],
    ],
    variants: [
      { suffix: "de Frango", multiplier: 1, popularity: 1 },
      { suffix: "de Ricota com Espinafre", multiplier: 1.08, popularity: 0.7, extraRecipe: [["Ricota", 0.05], ["Espinafre", 0.03]] },
      { suffix: "de Presunto e Queijo", multiplier: 1.12, popularity: 0.65, extraRecipe: [["Presunto", 0.04], ["Queijo Mussarela", 0.04]] },
      { suffix: "Premium", multiplier: 1.18, popularity: 0.55 },
    ],
  },
  {
    name: "Enroladinho",
    category: "Salgados",
    basePrice: 6.9,
    popularity: 4.6,
    quantityRange: [1, 4],
    recipe: [
      ["Farinha de Trigo", 0.1],
      ["Manteiga", 0.02],
      ["Fermento Biologico", 0.01],
    ],
    variants: [
      { suffix: "de Salsicha", multiplier: 1, popularity: 1, extraRecipe: [["Salsicha", 0.05]] },
      { suffix: "de Queijo", multiplier: 1.06, popularity: 0.8, extraRecipe: [["Queijo Mussarela", 0.04]] },
      { suffix: "de Presunto e Queijo", multiplier: 1.1, popularity: 0.75, extraRecipe: [["Presunto", 0.03], ["Queijo Mussarela", 0.03]] },
      { suffix: "Assado", multiplier: 1.08, popularity: 0.7, extraRecipe: [["Salsicha", 0.05]] },
    ],
  },
  {
    name: "Cafe Coado",
    category: "Bebidas",
    basePrice: 5.2,
    popularity: 9.5,
    quantityRange: [1, 3],
    recipe: [
      ["Cafe Moido", 0.02],
      ["Acucar", 0.005],
    ],
    variants: [
      { suffix: "Pequeno", multiplier: 1, popularity: 1 },
      { suffix: "Medio", multiplier: 1.18, popularity: 0.95, recipeMultiplier: 1.2 },
      { suffix: "Grande", multiplier: 1.34, popularity: 0.75, recipeMultiplier: 1.45 },
      { suffix: "sem Acucar", multiplier: 1, popularity: 0.55, omitIngredients: ["Acucar"] },
    ],
  },
  {
    name: "Cafe com Leite",
    category: "Bebidas",
    basePrice: 6.8,
    popularity: 6.8,
    quantityRange: [1, 3],
    recipe: [
      ["Cafe Moido", 0.02],
      ["Leite", 0.18],
      ["Acucar", 0.005],
    ],
    variants: [
      { suffix: "Pequeno", multiplier: 1, popularity: 1 },
      { suffix: "Medio", multiplier: 1.15, popularity: 0.95, recipeMultiplier: 1.15 },
      { suffix: "Grande", multiplier: 1.3, popularity: 0.7, recipeMultiplier: 1.35 },
      { suffix: "Cremoso", multiplier: 1.18, popularity: 0.65, extraRecipe: [["Leite em Po", 0.01]] },
    ],
  },
  {
    name: "Cappuccino",
    category: "Bebidas",
    basePrice: 8.4,
    popularity: 4.4,
    quantityRange: [1, 2],
    recipe: [
      ["Cafe Moido", 0.02],
      ["Leite", 0.15],
      ["Chocolate em Po", 0.01],
      ["Canela", 0.002],
    ],
    variants: [
      { suffix: "Tradicional", multiplier: 1, popularity: 1 },
      { suffix: "Grande", multiplier: 1.22, popularity: 0.75, recipeMultiplier: 1.25 },
      { suffix: "com Chantilly", multiplier: 1.26, popularity: 0.7, extraRecipe: [["Chantilly", 0.03]] },
      { suffix: "Especial", multiplier: 1.18, popularity: 0.6 },
    ],
  },
  {
    name: "Chocolate Quente",
    category: "Bebidas",
    basePrice: 8.8,
    popularity: 3.6,
    quantityRange: [1, 2],
    recipe: [
      ["Leite", 0.2],
      ["Chocolate em Po", 0.03],
      ["Acucar", 0.01],
    ],
    variants: [
      { suffix: "Tradicional", multiplier: 1, popularity: 1 },
      { suffix: "com Chantilly", multiplier: 1.18, popularity: 0.75, extraRecipe: [["Chantilly", 0.03]] },
      { suffix: "Cremoso", multiplier: 1.14, popularity: 0.7, extraRecipe: [["Leite em Po", 0.01]] },
      { suffix: "Premium", multiplier: 1.22, popularity: 0.55, extraRecipe: [["Cacau", 0.02]] },
    ],
  },
  {
    name: "Suco de Laranja",
    category: "Bebidas",
    basePrice: 7.4,
    popularity: 5.2,
    quantityRange: [1, 2],
    recipe: [["Laranja", 0.25]],
    variants: [
      { suffix: "300ml", multiplier: 1, popularity: 1 },
      { suffix: "500ml", multiplier: 1.22, popularity: 0.85, recipeMultiplier: 1.45 },
      { suffix: "Natural", multiplier: 1.08, popularity: 0.8 },
      { suffix: "com Gelo", multiplier: 1, popularity: 0.55 },
    ],
  },
  {
    name: "Cha Gelado",
    category: "Bebidas",
    basePrice: 6.9,
    popularity: 2.8,
    quantityRange: [1, 2],
    recipe: [
      ["Cha Preto", 0.01],
      ["Acucar", 0.01],
    ],
    variants: [
      { suffix: "de Limao", multiplier: 1, popularity: 1, extraRecipe: [["Limao", 0.05]] },
      { suffix: "de Maracuja", multiplier: 1.12, popularity: 0.75, extraRecipe: [["Maracuja", 0.05]] },
      { suffix: "Natural", multiplier: 1.05, popularity: 0.7 },
      { suffix: "500ml", multiplier: 1.18, popularity: 0.6, recipeMultiplier: 1.4 },
    ],
  },
  {
    name: "Iogurte com Frutas",
    category: "Bebidas",
    basePrice: 9.2,
    popularity: 2.4,
    quantityRange: [1, 2],
    recipe: [
      ["Iogurte", 0.18],
      ["Granola", 0.03],
    ],
    variants: [
      { suffix: "com Morango", multiplier: 1, popularity: 1, extraRecipe: [["Morango", 0.04]] },
      { suffix: "com Banana", multiplier: 1.02, popularity: 0.85, extraRecipe: [["Banana", 0.05]] },
      { suffix: "com Maca", multiplier: 1.04, popularity: 0.7, extraRecipe: [["Maca", 0.05]] },
      { suffix: "Especial", multiplier: 1.1, popularity: 0.55 },
    ],
  },
];

const SIZE_PRESETS = {
  small: {
    clientes: 30,
    funcionarios: 6,
    ingredientes: 15,
    produtos: 20,
    pedidos: 150,
  },
  medium: {
    clientes: 200,
    funcionarios: 15,
    ingredientes: 30,
    produtos: 50,
    pedidos: 2000,
  },
  large: {
    clientes: 1000,
    funcionarios: 40,
    ingredientes: 60,
    produtos: 120,
    pedidos: 15000,
  },
};

module.exports = {
  FIRST_NAMES,
  INGREDIENT_CATALOG,
  LAST_NAMES,
  PRODUCT_FAMILIES,
  SIZE_PRESETS,
};
