const TABLE_DEFINITIONS = {
  clientes: {
    collection: "clientes",
    pk: ["id"],
    autoId: true,
    insertColumns: ["nome", "cpf"],
    updateColumns: ["nome", "cpf"],
    defaultSort: { column: "id", order: "asc" },
    fields: {
      id: { type: "integer", generated: true, sortable: true, filterable: true },
      nome: {
        type: "text",
        required: true,
        allowEmpty: false,
        sortable: true,
        filterable: true,
        allowLike: true,
      },
      cpf: {
        type: "text",
        required: true,
        allowEmpty: false,
        sortable: true,
        filterable: true,
      },
    },
    createSql: `
      CREATE TABLE IF NOT EXISTS clientes (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        nome TEXT NOT NULL,
        cpf TEXT NOT NULL UNIQUE
      );
    `,
    seedRows: [
      { id: 1, nome: "Maria Silva", cpf: "111.111.111-11" },
      { id: 2, nome: "Joao Souza", cpf: "222.222.222-22" },
      { id: 3, nome: "Paula Mendes", cpf: "333.333.333-33" },
      { id: 4, nome: "Rafael Martins", cpf: "444.444.444-44" },
      { id: 5, nome: "Camila Rocha", cpf: "555.555.555-55" },
      { id: 6, nome: "Bruno Almeida", cpf: "666.666.666-66" },
      { id: 7, nome: "Lucia Fernandes", cpf: "777.777.777-77" },
      { id: 8, nome: "Igor Ribeiro", cpf: "888.888.888-88" },
      { id: 9, nome: "Marina Oliveira", cpf: "999.999.999-99" },
      { id: 10, nome: "Thiago Nunes", cpf: "101.101.101-10" },
    ],
  },
  funcionarios: {
    collection: "funcionarios",
    pk: ["id"],
    autoId: true,
    insertColumns: ["nome"],
    updateColumns: ["nome"],
    defaultSort: { column: "id", order: "asc" },
    fields: {
      id: { type: "integer", generated: true, sortable: true, filterable: true },
      nome: {
        type: "text",
        required: true,
        allowEmpty: false,
        sortable: true,
        filterable: true,
        allowLike: true,
      },
    },
    createSql: `
      CREATE TABLE IF NOT EXISTS funcionarios (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        nome TEXT NOT NULL
      );
    `,
    seedRows: [
      { id: 1, nome: "Ana Costa" },
      { id: 2, nome: "Carlos Lima" },
      { id: 3, nome: "Beatriz Prado" },
      { id: 4, nome: "Daniel Moraes" },
      { id: 5, nome: "Elaine Barros" },
      { id: 6, nome: "Felipe Araujo" },
      { id: 7, nome: "Gabriela Pinto" },
      { id: 8, nome: "Henrique Torres" },
      { id: 9, nome: "Isabela Gomes" },
      { id: 10, nome: "Juliano Teixeira" },
    ],
  },
  pedidos: {
    collection: "pedidos",
    pk: ["id"],
    autoId: true,
    insertColumns: ["data", "total", "id_cliente", "id_funcionario"],
    updateColumns: ["data", "total", "id_cliente", "id_funcionario"],
    defaultSort: { column: "data", order: "desc" },
    fields: {
      id: { type: "integer", generated: true, sortable: true, filterable: true },
      data: {
        type: "datetime",
        required: true,
        allowEmpty: false,
        sortable: true,
        filterable: true,
        allowRange: true,
      },
      total: {
        type: "real",
        required: true,
        min: 0,
        sortable: true,
        filterable: true,
        allowRange: true,
      },
      id_cliente: {
        type: "integer",
        required: true,
        sortable: true,
        filterable: true,
        allowRange: true,
        references: { collection: "clientes", field: "id" },
      },
      id_funcionario: {
        type: "integer",
        required: true,
        sortable: true,
        filterable: true,
        allowRange: true,
        references: { collection: "funcionarios", field: "id" },
      },
    },
    createSql: `
      CREATE TABLE IF NOT EXISTS pedidos (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        data TEXT NOT NULL,
        total REAL NOT NULL CHECK (total >= 0),
        id_cliente INTEGER NOT NULL,
        id_funcionario INTEGER NOT NULL,
        FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON UPDATE CASCADE ON DELETE RESTRICT,
        FOREIGN KEY (id_funcionario) REFERENCES funcionarios(id) ON UPDATE CASCADE ON DELETE RESTRICT
      );
    `,
    seedRows: [
      {
        id: 1,
        data: "2026-04-08T09:00",
        total: 1.8,
        id_cliente: 1,
        id_funcionario: 2,
      },
      {
        id: 2,
        data: "2026-04-08T10:10",
        total: 28.0,
        id_cliente: 2,
        id_funcionario: 1,
      },
      {
        id: 3,
        data: "2026-04-08T11:35",
        total: 11.0,
        id_cliente: 3,
        id_funcionario: 3,
      },
      {
        id: 4,
        data: "2026-04-08T13:20",
        total: 8.5,
        id_cliente: 4,
        id_funcionario: 4,
      },
      {
        id: 5,
        data: "2026-04-08T15:00",
        total: 21.0,
        id_cliente: 5,
        id_funcionario: 5,
      },
      {
        id: 6,
        data: "2026-04-08T16:25",
        total: 18.0,
        id_cliente: 6,
        id_funcionario: 6,
      },
      {
        id: 7,
        data: "2026-04-08T17:10",
        total: 8.4,
        id_cliente: 7,
        id_funcionario: 7,
      },
      {
        id: 8,
        data: "2026-04-08T18:05",
        total: 35.0,
        id_cliente: 8,
        id_funcionario: 8,
      },
      {
        id: 9,
        data: "2026-04-08T19:30",
        total: 12.0,
        id_cliente: 9,
        id_funcionario: 9,
      },
      {
        id: 10,
        data: "2026-04-08T20:15",
        total: 18.0,
        id_cliente: 10,
        id_funcionario: 10,
      },
    ],
  },
  itensPedido: {
    collection: "itensPedido",
    pk: ["id_pedido", "id_produto"],
    autoId: false,
    insertColumns: ["id_pedido", "id_produto", "quantidade", "valor_unitario"],
    updateColumns: ["quantidade", "valor_unitario"],
    defaultSort: { column: "id_pedido", order: "asc" },
    fields: {
      id_pedido: {
        type: "integer",
        required: true,
        sortable: true,
        filterable: true,
        allowRange: true,
        references: { collection: "pedidos", field: "id" },
      },
      id_produto: {
        type: "integer",
        required: true,
        sortable: true,
        filterable: true,
        allowRange: true,
        references: { collection: "produtos", field: "id" },
      },
      quantidade: {
        type: "real",
        required: true,
        min: 0.000001,
        sortable: true,
        filterable: true,
        allowRange: true,
      },
      valor_unitario: {
        type: "real",
        required: true,
        min: 0,
        sortable: true,
        filterable: true,
        allowRange: true,
      },
    },
    createSql: `
      CREATE TABLE IF NOT EXISTS itensPedido (
        id_pedido INTEGER NOT NULL,
        id_produto INTEGER NOT NULL,
        quantidade REAL NOT NULL CHECK (quantidade > 0),
        valor_unitario REAL NOT NULL CHECK (valor_unitario >= 0),
        PRIMARY KEY (id_pedido, id_produto),
        FOREIGN KEY (id_pedido) REFERENCES pedidos(id) ON UPDATE CASCADE ON DELETE RESTRICT,
        FOREIGN KEY (id_produto) REFERENCES produtos(id) ON UPDATE CASCADE ON DELETE RESTRICT
      );
    `,
    seedRows: [
      { id_pedido: 1, id_produto: 1, quantidade: 2, valor_unitario: 0.9 },
      { id_pedido: 2, id_produto: 2, quantidade: 1, valor_unitario: 28.0 },
      { id_pedido: 3, id_produto: 3, quantidade: 2, valor_unitario: 5.5 },
      { id_pedido: 4, id_produto: 4, quantidade: 1, valor_unitario: 8.5 },
      { id_pedido: 5, id_produto: 5, quantidade: 3, valor_unitario: 7.0 },
      { id_pedido: 6, id_produto: 6, quantidade: 1, valor_unitario: 18.0 },
      { id_pedido: 7, id_produto: 7, quantidade: 6, valor_unitario: 1.4 },
      { id_pedido: 8, id_produto: 8, quantidade: 10, valor_unitario: 3.5 },
      { id_pedido: 9, id_produto: 9, quantidade: 2, valor_unitario: 6.0 },
      { id_pedido: 10, id_produto: 10, quantidade: 2, valor_unitario: 9.0 },
    ],
  },
  produtos: {
    collection: "produtos",
    pk: ["id"],
    autoId: true,
    insertColumns: ["nome", "valor", "categoria"],
    updateColumns: ["nome", "valor", "categoria"],
    defaultSort: { column: "nome", order: "asc" },
    fields: {
      id: { type: "integer", generated: true, sortable: true, filterable: true },
      nome: {
        type: "text",
        required: true,
        allowEmpty: false,
        sortable: true,
        filterable: true,
        allowLike: true,
      },
      valor: {
        type: "real",
        required: true,
        min: 0,
        sortable: true,
        filterable: true,
        allowRange: true,
      },
      categoria: {
        type: "text",
        required: true,
        allowEmpty: false,
        sortable: true,
        filterable: true,
        allowLike: true,
      },
    },
    createSql: `
      CREATE TABLE IF NOT EXISTS produtos (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        nome TEXT NOT NULL,
        valor REAL NOT NULL CHECK (valor >= 0),
        categoria TEXT NOT NULL
      );
    `,
    seedRows: [
      { id: 1, nome: "Pao Frances", valor: 0.9, categoria: "Panificacao" },
      { id: 2, nome: "Bolo de Cenoura", valor: 28.0, categoria: "Confeitaria" },
      { id: 3, nome: "Cafe Coado", valor: 5.5, categoria: "Bebidas" },
      { id: 4, nome: "Croissant de Manteiga", valor: 8.5, categoria: "Panificacao" },
      { id: 5, nome: "Sonho de Creme", valor: 7.0, categoria: "Confeitaria" },
      { id: 6, nome: "Quiche de Alho-Poro", valor: 18.0, categoria: "Salgados" },
      { id: 7, nome: "Pao Integral", valor: 1.4, categoria: "Panificacao" },
      { id: 8, nome: "Brigadeiro Gourmet", valor: 3.5, categoria: "Confeitaria" },
      { id: 9, nome: "Suco de Laranja", valor: 6.0, categoria: "Bebidas" },
      { id: 10, nome: "Empada de Frango", valor: 9.0, categoria: "Salgados" },
    ],
  },
  produtosIngredientes: {
    collection: "produtosIngredientes",
    pk: ["id_produto", "id_ingrediente"],
    autoId: false,
    insertColumns: ["id_produto", "id_ingrediente", "quantidade"],
    updateColumns: ["quantidade"],
    defaultSort: { column: "id_produto", order: "asc" },
    fields: {
      id_produto: {
        type: "integer",
        required: true,
        sortable: true,
        filterable: true,
        allowRange: true,
        references: { collection: "produtos", field: "id" },
      },
      id_ingrediente: {
        type: "integer",
        required: true,
        sortable: true,
        filterable: true,
        allowRange: true,
        references: { collection: "ingredientes", field: "id" },
      },
      quantidade: {
        type: "real",
        required: true,
        min: 0.000001,
        sortable: true,
        filterable: true,
        allowRange: true,
      },
    },
    createSql: `
      CREATE TABLE IF NOT EXISTS produtosIngredientes (
        id_produto INTEGER NOT NULL,
        id_ingrediente INTEGER NOT NULL,
        quantidade REAL NOT NULL CHECK (quantidade > 0),
        PRIMARY KEY (id_produto, id_ingrediente),
        FOREIGN KEY (id_produto) REFERENCES produtos(id) ON UPDATE CASCADE ON DELETE RESTRICT,
        FOREIGN KEY (id_ingrediente) REFERENCES ingredientes(id) ON UPDATE CASCADE ON DELETE RESTRICT
      );
    `,
    seedRows: [
      { id_produto: 1, id_ingrediente: 1, quantidade: 0.2 },
      { id_produto: 1, id_ingrediente: 3, quantidade: 0.01 },
      { id_produto: 2, id_ingrediente: 1, quantidade: 0.35 },
      { id_produto: 2, id_ingrediente: 2, quantidade: 0.2 },
      { id_produto: 3, id_ingrediente: 4, quantidade: 0.05 },
      { id_produto: 2, id_ingrediente: 5, quantidade: 3 },
      { id_produto: 3, id_ingrediente: 2, quantidade: 0.01 },
      { id_produto: 4, id_ingrediente: 1, quantidade: 0.12 },
      { id_produto: 4, id_ingrediente: 7, quantidade: 0.03 },
      { id_produto: 5, id_ingrediente: 1, quantidade: 0.1 },
      { id_produto: 5, id_ingrediente: 2, quantidade: 0.08 },
      { id_produto: 5, id_ingrediente: 6, quantidade: 0.05 },
      { id_produto: 6, id_ingrediente: 1, quantidade: 0.15 },
      { id_produto: 6, id_ingrediente: 9, quantidade: 0.12 },
      { id_produto: 6, id_ingrediente: 6, quantidade: 0.03 },
      { id_produto: 7, id_ingrediente: 1, quantidade: 0.25 },
      { id_produto: 7, id_ingrediente: 3, quantidade: 0.01 },
      { id_produto: 8, id_ingrediente: 8, quantidade: 0.04 },
      { id_produto: 8, id_ingrediente: 2, quantidade: 0.02 },
      { id_produto: 9, id_ingrediente: 10, quantidade: 0.2 },
      { id_produto: 10, id_ingrediente: 1, quantidade: 0.1 },
      { id_produto: 10, id_ingrediente: 9, quantidade: 0.08 },
    ],
  },
  ingredientes: {
    collection: "ingredientes",
    pk: ["id"],
    autoId: true,
    insertColumns: ["nome", "unidade", "quantidade_estoque"],
    updateColumns: ["nome", "unidade", "quantidade_estoque"],
    defaultSort: { column: "nome", order: "asc" },
    fields: {
      id: { type: "integer", generated: true, sortable: true, filterable: true },
      nome: {
        type: "text",
        required: true,
        allowEmpty: false,
        sortable: true,
        filterable: true,
        allowLike: true,
      },
      unidade: {
        type: "text",
        required: true,
        allowEmpty: false,
        sortable: true,
        filterable: true,
      },
      quantidade_estoque: {
        type: "real",
        required: true,
        min: 0,
        sortable: true,
        filterable: true,
        allowRange: true,
      },
    },
    createSql: `
      CREATE TABLE IF NOT EXISTS ingredientes (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        nome TEXT NOT NULL,
        unidade TEXT NOT NULL,
        quantidade_estoque REAL NOT NULL CHECK (quantidade_estoque >= 0)
      );
    `,
    seedRows: [
      { id: 1, nome: "Farinha", unidade: "kg", quantidade_estoque: 50 },
      { id: 2, nome: "Acucar", unidade: "kg", quantidade_estoque: 25 },
      { id: 3, nome: "Fermento", unidade: "kg", quantidade_estoque: 8 },
      { id: 4, nome: "Cafe", unidade: "kg", quantidade_estoque: 6 },
      { id: 5, nome: "Ovos", unidade: "un", quantidade_estoque: 120 },
      { id: 6, nome: "Leite", unidade: "l", quantidade_estoque: 40 },
      { id: 7, nome: "Manteiga", unidade: "kg", quantidade_estoque: 15 },
      { id: 8, nome: "Chocolate", unidade: "kg", quantidade_estoque: 12 },
      { id: 9, nome: "Frango", unidade: "kg", quantidade_estoque: 18 },
      { id: 10, nome: "Laranja", unidade: "kg", quantidade_estoque: 20 },
    ],
  },
};

const SEED_ORDER = [
  "clientes",
  "funcionarios",
  "produtos",
  "ingredientes",
  "pedidos",
  "itensPedido",
  "produtosIngredientes",
];

const TABLE_NAMES = Object.keys(TABLE_DEFINITIONS);

module.exports = {
  SEED_ORDER,
  TABLE_DEFINITIONS,
  TABLE_NAMES,
};
