CREATE TABLE IF NOT EXISTS pedidos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  data TEXT NOT NULL,
  total REAL NOT NULL CHECK (total >= 0),
  id_cliente INTEGER NOT NULL,
  id_funcionario INTEGER NOT NULL,
  FOREIGN KEY (id_cliente) REFERENCES clientes(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (id_funcionario) REFERENCES funcionarios(id) ON UPDATE CASCADE ON DELETE RESTRICT
);
